language: go

go:
  - 1.11.x

before_install:
  - go get -t -v ./...
  - go get github.com/axw/gocov/gocov

script:
  - gocov test -v ./... > coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
