// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import time "time"

// PatternInterface is an autogenerated mock type for the PatternInterface type
type PatternInterface struct {
	mock.Mock
}

// IsBeyondPattern provides a mock function with given fields: n
func (_m *PatternInterface) IsBeyondPattern(n time.Time) bool {
	ret := _m.Called(n)

	var r0 bool
	if rf, ok := ret.Get(0).(func(time.Time) bool); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ResolveInstance provides a mock function with given fields: n
func (_m *PatternInterface) ResolveInstance(n time.Time) time.Time {
	ret := _m.Called(n)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(time.Time) time.Time); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
