// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import time "time"

// PeriodInterface is an autogenerated mock type for the PeriodInterface type
type PeriodInterface struct {
	mock.Mock
}

// ResolveEnd provides a mock function with given fields:
func (_m *PeriodInterface) ResolveEnd() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// ResolveStart provides a mock function with given fields:
func (_m *PeriodInterface) ResolveStart() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
