// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import task "project.scmp.tech/technology/newsroom-system/assignment/cmd/cronjob/task"
import time "time"

// ScheduleInterface is an autogenerated mock type for the ScheduleInterface type
type ScheduleInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: planName, t, forceRun, forceInstance, noRecord, currentTime
func (_m *ScheduleInterface) Execute(planName string, t task.TaskInterface, forceRun string, forceInstance int, noRecord int, currentTime time.Time) {
	_m.Called(planName, t, forceRun, forceInstance, noRecord, currentTime)
}
