// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import period "project.scmp.tech/technology/newsroom-system/assignment/cmd/cronjob/period"

// TaskInterface is an autogenerated mock type for the TaskInterface type
type TaskInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: p
func (_m *TaskInterface) Execute(p period.PeriodInterface) (bool, error) {
	ret := _m.Called(p)

	var r0 bool
	if rf, ok := ret.Get(0).(func(period.PeriodInterface) bool); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(period.PeriodInterface) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
